'use client';
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowRight, ArrowLeft, Vote, Sparkles, Landmark, Building2, House, ScrollText, FileQuestion, MapPin, BookOpen, Check, Mail, LockKeyhole, ExternalLink, Layers } from 'lucide-react';
import { DistrictMap } from '@/components/ballot/DistrictMap';
import { DISTRICT_LAYERS, OFFICIAL_LINKS } from '@/lib/civic';
import { useDemoTool } from '@/components/ballot/useDemoTool';
import { CivicTour } from '@/components/tour/CivicTour';
import { useReducedMotion } from '@/components/tour/useReducedMotion';
import { DEMO_DISTRICTS, type BallotDoor } from '@/lib/ballot-tour';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
const tutorials=[
 {word:'WHO',title:'are you voting for?',text:'Some parts of your ballot are elections between people running for public office.',aside:'Different offices. Different jobs. Same ballot.',items:[{icon:Landmark,name:'Federal',desc:'Your voice in Washington.'},{icon:Building2,name:'State',desc:'Decisions for Hawaiʻi.'},{icon:House,name:'Local',desc:'Government closer to home.'}]},
 {word:'WHAT',title:'are you voting on?',text:'Not everything on your ballot is a person.',detail:'Some questions ask voters to approve or reject changes to laws, constitutions, or local government rules.',aside:'A question mark isn’t a jump scare.',items:[{icon:ScrollText,name:'State questions',desc:'Changes at the state level.'},{icon:FileQuestion,name:'County questions',desc:'Changes closer to home.'}]},
 {word:'HOW',title:'do you actually vote?',text:'Four steps. One less thing to be afraid of.',aside:'Democracy: surprisingly paperwork-heavy.',items:[{icon:MapPin,name:'Find your ballot.',desc:''},{icon:BookOpen,name:'Learn what’s on it.',desc:''},{icon:Check,name:'Make your choices.',desc:''},{icon:Mail,name:'Return it correctly and on time.',desc:''}]},
];
export default function Home(){
 const [screen,setScreen]=useState(0);const [address,setAddress]=useState('');const [selected,setSelected]=useState(false);const [layer,setLayer]=useState('0');const [future,setFuture]=useState<'who'|'what'|null>(null);
 const [tour,setTour]=useState(false);const [portal,setPortal]=useState<'idle'|'reveal'|'zoom'>('idle');const [visited,setVisited]=useState<BallotDoor[]>([]);
 const mapPortal=useRef<HTMLDivElement>(null);const reducedMotion=useReducedMotion();
 const markVisited=useCallback((door:BallotDoor)=>setVisited(previous=>previous.includes(door)?previous:[...previous,door]),[]);
 useEffect(()=>{if(portal==='idle')return; if(portal==='reveal')mapPortal.current?.scrollIntoView({block:'start',behavior:'instant'});const timer=window.setTimeout(()=>{if(portal==='reveal'&&!reducedMotion)setPortal('zoom');else {setTour(true);setPortal('idle')}},portal==='reveal'?1200:1000);return()=>window.clearTimeout(timer)},[portal,reducedMotion]);
 useDemoTool(useCallback(()=>{setScreen(4);setSelected(true);setAddress('');setFuture(null);setTour(false);setPortal('reveal')},[]));
 const heading=useRef<HTMLHeadingElement>(null);const start=useRef<{x:number;y:number}|null>(null);
 useEffect(()=>{heading.current?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});},[screen,future,tour]);
 function go(n:number){setPortal('idle');setTour(false);setScreen(Math.max(0,Math.min(4,n)));setFuture(null)}
 function submit(e:FormEvent){e.preventDefault();if(!address.trim())return;setSelected(true);setAddress('');setPortal('reveal')}
 const tutorial=tutorials[screen-1];
 return <main className="stage"><div className="masthead"><span>AN EVENING OF CIVIC CURIOSITY</span><span>HAWAIʻI · NONPARTISAN</span></div>
 {tour?<CivicTour context={DEMO_DISTRICTS} visited={visited} onVisited={markVisited} onBackToMap={()=>{setTour(false);setPortal('idle')}}/>:<section key={`${screen}-${future}`} className={`poster ${screen===0?'welcome':screen===4?'workspace':'lesson'}`} onTouchStart={e=>{if(screen<1||screen>3)return;start.current={x:e.touches[0].clientX,y:e.touches[0].clientY}}} onTouchEnd={e=>{if(!start.current)return;const dx=e.changedTouches[0].clientX-start.current.x,dy=e.changedTouches[0].clientY-start.current.y;start.current=null;if(Math.abs(dx)>80&&Math.abs(dx)>Math.abs(dy)*1.5)go(screen+(dx<0?1:-1))}}>
 {screen===0?<><div className="eyebrow">A PERFECTLY CIVIL HORROR SHOW</div><div className="title-block"><h1 tabIndex={-1} ref={heading}>BALLOTS<span className="amp">&</span><span>BOOZE</span></h1><div className="subtitle">THE HORRORS OF NOT VOTING</div></div><div className="ticket"><Vote size={34} strokeWidth={1.5}/><span>NO EXPERIENCE NECESSARY.<br/>JUST A LITTLE CURIOSITY.</span><Sparkles size={24}/></div><p className="intro">Enter at your own risk.<br/>You may leave knowing<br/><em>what a district is.</em></p><p className="reassure">We’re making your ballot a lot less terrifying.</p><button className="primary" onClick={()=>go(1)}>ENTER IF YOU DARE <ArrowRight/></button><p className="fine">A little camp. A lot less confusion. Your choices.</p></>:
 screen<4?<><div className="lesson-top"><button className="back" onClick={()=>go(screen-1)} aria-label="Go back"><ArrowLeft size={20}/> BACK</button><span>THE SURVIVAL GUIDE</span></div><div className="chapter">CHAPTER 0{screen}</div><h2 ref={heading} tabIndex={-1}><strong>{tutorial.word}</strong><span>{tutorial.title}</span></h2><p className="lesson-copy">{tutorial.text}</p>{tutorial.detail&&<p className="detail">{tutorial.detail}</p>}<div className={`examples ${screen===3?'steps':''}`}>{tutorial.items.map((item,i)=><div className="example" key={item.name}><div className="icon-stamp"><item.icon size={29} strokeWidth={1.5}/></div><div><h3>{item.name}</h3>{item.desc&&<p>{item.desc}</p>}</div>{screen===3&&<span className="step-number">0{i+1}</span>}</div>)}</div><p className="aside">{tutorial.aside}</p><div className="lesson-bottom"><div className="progress"><span>{screen} / 3</span><div aria-label={`Tutorial ${screen} of 3`}>{[1,2,3].map(n=><i key={n} className={n<=screen?'complete':''}/>)}</div><span>SWIPE OR TAP</span></div><button className="primary" onClick={()=>go(screen+1)}>{screen===3?'SHOW ME MY BALLOT':'NEXT'} <ArrowRight/></button></div></>:
 future?<><button className="back" onClick={()=>setFuture(null)}><ArrowLeft size={20}/> BACK TO MY DISTRICTS</button><div className="chapter">THE NEXT CHAPTER</div><h2 ref={heading} tabIndex={-1}><strong>{future==='who'?'WHO':'WHAT'}</strong><span>is on my ballot?</span></h2><div className="coming"><Vote size={58} strokeWidth={1}/><h3>Coming attractions.</h3><p>{future==='who'?'Neutral candidate information will live here.':'Plain-language ballot questions and amendments will live here.'}</p><p>This prototype stops at district discovery. No candidate or ballot recommendations.</p></div><a className="primary" href={OFFICIAL_LINKS.ballot} target="_blank" rel="noopener noreferrer">OFFICIAL BALLOT LOOKUP <ExternalLink size={20}/></a></>:
 <><div className="lesson-top"><button className="back" onClick={()=>go(3)}><ArrowLeft size={20}/> BACK</button><span className="demo-tag">PROTOTYPE · DEMO DATA</span></div><div className="chapter">LOCATION, LOCATION… LEGISLATION.</div><h2 className="address-heading" tabIndex={-1} ref={heading}>YOUR ADDRESS<br/><em>DECIDES</em> YOUR BALLOT</h2><p className="lesson-copy">Where you live determines your voting districts — and which races appear on your ballot.</p><form onSubmit={submit}><label htmlFor="address">Enter your Hawaiʻi address</label><div className="address-input"><MapPin size={21}/><input id="address" name="address" autoComplete="off" value={address} onChange={e=>{setAddress(e.target.value);setSelected(false);setPortal('idle')}} placeholder="123 Example St, Honolulu, HI" required maxLength={200}/></div><button className="demo-fill" type="button" onClick={()=>{setAddress('123 Example St, Honolulu, HI');setSelected(false);setPortal('idle')}}>Try a demo address</button><button className="primary" type="submit">FIND MY DISTRICTS <ArrowRight size={21}/></button><p className="privacy"><LockKeyhole size={16}/><span>We only use your address to identify your voting districts.</span></p><p className="demo-note">Demo only: no address lookup runs. Nothing you enter is sent or saved, and every address shows the same example.</p></form>
 <div className="layer-title"><Layers size={17}/><span>ONE HOME. SEVERAL DISTRICTS.</span></div><Tabs value={layer} onValueChange={setLayer}><TabsList className="layer-tabs">{DISTRICT_LAYERS.map((l,i)=><TabsTrigger className="layer-tab" value={String(i)} key={l.name}>{l.short}</TabsTrigger>)}</TabsList></Tabs><div ref={mapPortal} className={`map-portal ${portal==='zoom'?'portal-zoom':''}`}><DistrictMap selected={selected} layer={Number(layer)}/>{portal!=='idle'&&<div className="portal-title" role="status">YOUR DEMO DISTRICTS ARE REVEALED.<br/><strong>ENTER YOUR DISTRICT…</strong></div>}</div>
 <div aria-live="polite">{selected&&<div className="district-results"><div className="result-heading"><h3>YOUR DISTRICTS</h3><span>DEMO ONLY</span></div><p>These are fictional labels, not your matched districts.</p><dl>{DISTRICT_LAYERS.map(l=><div key={l.name}><dt>{l.name} District</dt><dd>{l.demo}</dd></div>)}</dl><a href={OFFICIAL_LINKS.ballot} target="_blank" rel="noopener noreferrer">Find your actual ballot on Hawaii.gov <ExternalLink size={15}/></a></div>}</div>
 {selected&&<div className="tour-invitation"><p>Every door leads to a different layer of government.</p><button className="primary" onClick={()=>{mapPortal.current?.scrollIntoView({block:'start',behavior:'instant'});if(reducedMotion){setTour(true);setPortal('idle')}else setPortal('zoom')}}>ENTER YOUR DISTRICT <ArrowRight/></button>{portal!=='idle'&&<button className="pause-tour" onClick={()=>setPortal('idle')}>Stay and review my districts first</button>}</div>}
 <div className="registration"><Mail size={24}/><div><h3>Make sure your ballot finds you.</h3><p>Register or update your mailing address on Hawaiʻi’s official website.</p><a href={OFFICIAL_LINKS.registration} target="_blank" rel="noopener noreferrer">REGISTER / UPDATE REGISTRATION <ExternalLink size={16}/></a></div></div><p className="fine">Independent, nonpartisan prototype. <a href={OFFICIAL_LINKS.districts} target="_blank" rel="noopener noreferrer">Official district information ↗</a></p></>}
 </section>}<footer>BALLOTS & BOOZE · YOUR BALLOT. YOUR CALL.<br/><span>NOT AN OFFICIAL ELECTION SERVICE</span></footer></main>
}
